services:
  srv-caamaconecta:
    image: bitnami/postgresql:latest
    container_name: caamaconecta
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=caamaconecta-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/bitnami/postgresql

volumes:
  postgres-data: